application: antplanner-hrd
version: 2-1-0
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /robots.txt
  static_files: antplanner2/static/robots.txt
  upload: antplanner2/static/robots.txt

- url: /static
  static_dir: antplanner2/static

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest

- name: lxml
  version: latest

env_variables:
  USE_MEMCACHE: true